name: muse_api
description: api wrapper for muse.
version: 1.0.0
repository: https://github.com/double764/muse-dart

environment:
  sdk: ^3.0.1

dependencies:
  built_collection: ^5.1.1
  built_value: ^8.6.0
  http: ^1.0.0
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.4
  built_value_generator: ^8.6.0
  lints: ^2.0.0
  test: ^1.21.0
