name: muse_api
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.1

# Add regular dependencies here.
dependencies:
  built_collection: ^5.1.1
  built_value: ^8.6.0
  http: ^1.0.0
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.4
  built_value_generator: ^8.6.0
  lints: ^2.0.0
  test: ^1.21.0
